# From BaseImage:Tag
FROM ubuntu:latest
# Maintainer Info
MAINTAINER trickbooter <paul@trickbooter.com>

# Set an environment variable
ENV TERM linux

# Install base tools
# RUN apt-get update -y && apt-get install -y curl wget git tar unzip

# Docker has a default ENTRYPOINT of /bin/sh -c
# We can set our own default ENTRYPOINT
# ENTRYPOINT["bash"]

# Command sent from the CLI are appended to the default ENTRYPOINT
# CMD is executed on container run.
# CMD["some-script", "someparam"]