FROM ubuntu:latest
MAINTAINER trickbooter <paul@trickbooter.com>

ENV TERM linux

# install base tools
# RUN apt-get update -y && apt-get install -y curl wget git tar unzip

# Docker has a default ENTRYPOINT of /bin/sh -c
# We can set our own default ENTRYPOINT
# ENTRYPOINT["bash"]

# Command sent from the CLI are appended to the default ENTRYPOINT
# CMD is executed on container run.
# CMD["echo Hello World!"]